### PR TITLE
refactor tests

### PR DESCRIPTION
**Pull request by utnapischtim**
- refactor: solve caching problem in teardown
- tests: update expected output due to Babel upgrade

### CODE REVIEW

**Review by tmorrell — COMMENTED** [review]
These changes look fine, but I'm a little nervous about the data change format. It seems like the change with \u202 is also impacting invenio-rdm-records, which means that is might leak out via the API/UI. Does this indicate more re-configuration will be needed?

**Comment by utnapischtim** [comment]
I have the same problem with those changes, but nicola already did that with this [commit](https://github.com/inveniosoftware/invenio-rdm-records/pull/1225/commits/368778a9a98442ec96903e96e1686a9dc47115a2)

**Comment by fenekku** [comment]
Coordination:

Since @ntarocco was mentioned in the comments, adding him as reviewer to get this unblocked (if other translation expert, please notify!)

**Comment by ntarocco** [comment]
> These changes look fine, but I'm a little nervous about the data change format. It seems like the change with \u202 is also impacting invenio-rdm-records, which means that is might leak out via the API/UI. Does this indicate more re-configuration will be needed?

It should be correct indeed. This is needed because it was changed in the Unicode Common Locale Data Repository (CLDR) standard, see [here](https://unicode-org.atlassian.net/browse/CLDR-14032), and at some point, they updated the version of the standard in the babel, see [here](https://github.com/python-babel/babel/commit/d76db13414a6104019edc0dbafa82410e8d08e63).

**Review by ntarocco — APPROVED** [review]

**Pull request merged**
