### PR TITLE
Add language dropdown selector

### PR DESCRIPTION
**Pull request by andrewm89**
- addresses https://github.com/inveniosoftware/invenio-i18n/issues/40

### CODE REVIEW

**Comment by jirikuncar** [comment]
@andrewm89 thanks! The code looks good. Can you amend commit message so it follows the inveniosoftware style or shall I amend it during squash&merge?

**Comment by andrewm89** [comment]
@jirikuncar is it ok now?

**Comment by jirikuncar** [comment]
@andrewm89 almost :) `* Adds language dropdown macro.  (addresses #40)`

**Comment by andrewm89** [comment]
@jirikuncar third time lucky

**Comment by jirikuncar** [comment]
LGTM

**Pull request merged**
